"""create records table

Revision ID: 002
Revises: 001
Create Date: 2025-04-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
        sa.Column('id', sa.String(length=36), nullable=False, comment='记录ID (UUID)'),
        sa.Column('customer_id', sa.String(length=36), nullable=False, comment='所属客户ID'),
        sa.Column('content', sa.Text(), nullable=False, comment='沟通内容（原始文本）'),
        sa.Column('type', sa.String(length=20), server_default='text', nullable=False, comment='记录类型: text/audio'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_customer_id'), 'records', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_customer_id'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
