"""add original_name to transcriptions

Revision ID: 005
Revises: 004
Create Date: 2025-04-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 添加 original_name 字段，先允许 nullable
    op.add_column('transcriptions', sa.Column('original_name', sa.String(length=255), nullable=True, comment='用户原始上传文件名（展示用）'))
    
    # 2. 迁移数据：将现有 file_name 复制到 original_name
    op.execute("UPDATE transcriptions SET original_name = file_name WHERE original_name IS NULL")
    
    # 3. 修改字段为 non-nullable
    op.alter_column('transcriptions', 'original_name',
               existing_type=sa.String(length=255),
               nullable=False)
    
    # 4. 更新 file_name 字段注释
    op.alter_column('transcriptions', 'file_name',
               existing_type=sa.String(length=255),
               comment='安全文件名（用于 Storage）')
    
    # 5. 更新 file_path 字段注释
    op.alter_column('transcriptions', 'file_path',
               existing_type=sa.String(length=500),
               comment='Storage 完整路径')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptions', 'original_name')
    
    # 恢复注释
    op.alter_column('transcriptions', 'file_name',
               existing_type=sa.String(length=255),
               comment='原始文件名')
    
    op.alter_column('transcriptions', 'file_path',
               existing_type=sa.String(length=500),
               comment='Supabase Storage 文件路径')
    # ### end Alembic commands ###
