"""create customers table

Revision ID: 001
Revises: 
Create Date: 2025-04-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
        sa.Column('id', sa.String(length=36), nullable=False, comment='客户ID (UUID)'),
        sa.Column('user_id', sa.String(length=36), nullable=False, comment='所属用户ID'),
        sa.Column('name', sa.String(length=100), nullable=False, comment='客户姓名'),
        sa.Column('phone', sa.String(length=50), nullable=True, comment='客户电话'),
        sa.Column('gender', sa.String(length=20), nullable=True, comment='客户性别'),
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='客户标签列表'),
        sa.Column('summary_status', sa.String(length=20), server_default='stale', nullable=False, comment='总结状态: stale/updating/ready/failed'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (null表示未删除)'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
