"""update record type to support transcript

Revision ID: 004
Revises: 003
Create Date: 2025-04-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 更新 record 表的 type 字段，确保可以存储 'transcript'
    # 由于 SQLAlchemy String 不限制枚举值，这里只需更新注释
    op.alter_column('records', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment="记录类型: text/transcript",
               existing_nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment="记录类型: text/audio",
               existing_nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    # ### end Alembic commands ###
