"""add customer summary_text

Revision ID: 006
Revises: 005
Create Date: 2025-04-07 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('summary_text', sa.Text(), nullable=True, comment='AI生成的客户摘要'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'summary_text')
    # ### end Alembic commands ###
