"""create transcriptions table

Revision ID: 003
Revises: 002
Create Date: 2025-04-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcriptions',
        sa.Column('id', sa.String(length=36), nullable=False, comment='转写任务ID (UUID)'),
        sa.Column('customer_id', sa.String(length=36), nullable=False, comment='所属客户ID'),
        sa.Column('file_path', sa.String(length=500), nullable=False, comment='Supabase Storage 文件路径'),
        sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
        sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
        sa.Column('status', sa.String(length=20), server_default='uploaded', nullable=False, comment='状态: uploaded/transcribing/transcribed/confirmed/failed'),
        sa.Column('transcript_text', sa.Text(), nullable=True, comment='转写后的文本内容'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息（失败时填写）'),
        sa.Column('record_id', sa.String(length=36), nullable=True, comment='关联的 record ID（确认后生成）'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_customer_id'), 'transcriptions', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcriptions_customer_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    # ### end Alembic commands ###
