"""make transcription customer_id nullable

Revision ID: 7e03908c876c
Revises: 006
Create Date: 2026-04-10 02:15:57.775623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e03908c876c'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='记录类型: text/audio',
               existing_comment='记录类型: text/transcript',
               existing_nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('transcriptions', 'customer_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               comment='所属客户ID (可为空)',
               existing_comment='所属客户ID')
    op.drop_constraint('transcriptions_customer_id_fkey', 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.create_foreign_key('transcriptions_customer_id_fkey', 'transcriptions', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transcriptions', 'customer_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               comment='所属客户ID',
               existing_comment='所属客户ID (可为空)')
    op.alter_column('records', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='记录类型: text/transcript',
               existing_comment='记录类型: text/audio',
               existing_nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    # ### end Alembic commands ###
